name: Pull Request
on: pull_request
env:
  GO_VERSION: "1.17.x"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Go compiler
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Compile binaries
        run: go build -o gomaxscale cmd/gomaxscale/main.go

  lint:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Go compiler
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-go-installation: true
          skip-pkg-cache: false
          skip-build-cache: false
          only-new-issues: true # only check files change in the PR

  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Go compiler
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Recover Go Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go
          restore-keys: ${{ runner.os }}-go

      - name: Run Tests
        run: go test -v ./...